### PR TITLE
Update to version 2.0.27

### PR DESCRIPTION
**Pull request by lucenera**

### CODE REVIEW

**Comment by lucenera** [comment]
Let me know. I have already installed the module and it's fine. My changes are elementary.

**Comment by lindroidux** [comment]
The versioning is very strange from 2.8.7 to 1.0.
If the magisk module ID is same, it would have been reasonable not to change the original author. Pks refer development & versioning of optimized gps.conf

**Comment by lucenera** [comment]
I don't know what gps.conf means. However, the name derives from the fact that I was continuing to keep the form for myself and it doesn't change much if written 1 or 2 or 3. The form has another name if you noticed.  So it's the first version with this new name.  A version followed and updated.

**Comment by lindroidux** [comment]
1 or 2 or 3 does matter as far as dnscrypt protocols are concerned & the present protocol version is 2. The version now implemented, i.e 1 for the dnscrypt-proxy of blueneda lacks, is strange as it is not in step/tune with the ongoing progress/development (If u intent only to upgrade the binaries)

**Comment by lucenera** [comment]
It is not that the name was very explanatory before.  Otherwise it would have been called 2.0.25 and now 2.0.27.  There is a link to the jedisct1 page and it is explained that it is version 2 of dnscrypt-proxy, which follows the dnscrypt protocol in version 2. The version refers to the module, which is however an entity distinct from dnscrypt-  proxy of jedisct1 and the protocol, although it is connected.

**Pull request merged**
